# ndarrays en numpy

Este archivo contiene los siguientes temas: 
* Crear un ndarray de una dimensión (rank 1) 
* Crear un ndarray de dos dimensiones (rank 2)
* Otras manera de crear arrays en NumPy 

Algunos *shortcuts* útiles:
* tab --> ofrece sugerencias sobre funciones y atributos 
* shift + tab --> muestra la documentación  
* shift + enter --> run cell

Documentación de numpy: https://docs.scipy.org/doc/numpy/reference/

In [1]:
# Para trabajar con cualquiera de los objetos y funciones de numpy es necesario primero importar la libreria
# Por comodidad (y convención), lo renompramos como numpy
import numpy as np

-----

## Crear un ndarray de una dimensión (rank 1)

In [2]:
my_array = np.array([1,2,3,4,5])
print(my_array)
print('\nTipo del objeto: ', type(my_array))
print('\nForma (shape):', my_array.shape)

[1 2 3 4 5]

Tipo del objeto:  <class 'numpy.ndarray'>

Forma (shape): (5,)


In [3]:
# Como se trata de un array de una dimensión (rank 1), sólo necesitamos un índice para acceder a sus elementos
# Los índices en numpy comienzan en 0
print(my_array[0])
print(my_array[1])
print(my_array[2])

1
2
3


In [4]:
# Podemos cambiar el valor de los elementos de los arrays
my_array[3] = 1000
print(my_array)

[   1    2    3 1000    5]


-----

## Crear un ndarray de dos dimensiones (rank 2)


Un array de dos dimensiones es útil para representar matrices. Para crear una "matriz", se debe seguir el formato:  [ [renglón1] , [renglón2], ... ]

In [5]:
matrix = np.array([[11, 12, 13], 
                   [21, 22, 23], 
                   [31, 32, 33], 
                   [41, 42, 43]])
print(matrix)
print('\nTipo de objeto:', type(matrix))
print('\nForma del array:', matrix.shape)

# Usemos una manera alterna para imprimir en la consola:
print(f'\nEl array tiene {matrix.shape[0]} renglones y {matrix.shape[1]} columnas')

# [renglón, columna] --> formato para acceder a elementos específicos de un array de dos dimensiones
# OJO: Recordar que los ínidces comienzan en 0 
print(f'\nValor del elemento en [1,1]: {matrix[0,0]} \
       \nValor del elemento en [2,3]: {matrix[1,2]} \
       \nValor del elemento en [4,3]: {matrix[3,2]}')

[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]

Tipo de objeto: <class 'numpy.ndarray'>

Forma del array: (4, 3)

El array tiene 4 renglones y 3 columnas

Valor del elemento en [1,1]: 11        
Valor del elemento en [2,3]: 23        
Valor del elemento en [4,3]: 43


-------

## Otras maneras de crear arrays en NumPy

In [6]:
# Crear una matriz  de 3x4 (3 renglones y 4 columnas) cuyos valores son todos cero 
zero_matrix = np.zeros((3,4))
print(zero_matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
# Crear una matriz de 4x5 (4 renglones y 5 columnas) cuyos valores son todos unos
ones_matrix = np.ones((4,5))
print(ones_matrix)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [8]:
# Crear una matriz identidad de 3x3
id_matrix = np.eye(3, 3)
print(id_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
# Podemos utilizar el módulo random de numpy (numpy.random o, en nuestro caso, np.random) para crear matrices
# Crear una matriz de 3x3 cuyos elementos se distribuyen uniformemente entre 0 y 1
uniform_mat = np.random.random((3,3))
print(uniform_mat)

[[0.73125428 0.14113678 0.09227472]
 [0.57085112 0.17773604 0.44796836]
 [0.22304186 0.95748656 0.06753075]]


In [10]:
# Crear una matriz de 3x3 cuyos elementos se generan a partir de una distribución normal estándar
normal_mat = np.random.normal(0, 1, (3,3))
print(normal_mat)

[[ 0.10070256  1.13387068  0.20342587]
 [ 0.85875548  1.79128256 -0.45425458]
 [-1.87740575 -0.60635365 -0.67253848]]
